FROM nginx:1.24-alpine
COPY nginx/conf.d/default.conf /etc/nginx/conf.d/default.conf
COPY nginx/ssl /etc/nginx/ssl
COPY web-app/dist /usr/share/nginx/html/app
COPY web-admin/dist /usr/share/nginx/html/admin
